geocity/apps/submissions/urls.py
from django.urls import include, path

from . import views

app_name = "submissions"

submission_urlpatterns = [
    path(
        "administrative-entity/",
        views.submission_select_administrative_entity,
        name="submission_select_administrative_entity",
    ),
]

anonymous_submission_urlpatterns = [
    path(
        "anonymous/",
        views.anonymous_submission,
        name="anonymous_submission",
    ),
    path(
        "anonymous/sent",
        views.anonymous_submission_sent,
        name="anonymous_submission_sent",
    ),
]

existing_submission_urlpatterns = [
    path("", views.SubmissionDetailView.as_view(), name="submission_detail"),
    path(
        "objects/",
        views.submission_select_forms,
        name="submission_select_forms",
    ),
    path("properties/", views.submission_fields, name="submission_fields"),
    path("appendices/", views.submission_appendices, name="submission_appendices"),
    path("actors/", views.submission_contacts, name="submission_contacts"),
    path("submit/", views.submission_submit, name="submission_submit"),
    path(
        "submitconfirmed/",
        views.submission_submit_confirmed,
        name="submission_submit_confirmed",
    ),
    path("geotime/", views.submission_geo_time, name="submission_geo_time"),
    path("delete/", views.submission_delete, name="submission_delete"),
    path("approve/", views.submission_approve, name="submission_approve"),
    path("reject/", views.submission_reject, name="submission_reject"),
    path(
        "prolongation/",
        views.submission_prolongation,
        name="submission_prolongation",
    ),
]

urlpatterns = [
    path(
        "<int:submission_id>/",
        include(submission_urlpatterns + existing_submission_urlpatterns),
    ),
    # TODO: adapt path name here and in front app
    path(
        "permits-files/<path:path>",
        views.submission_file_download,
        name="submission_file_download",
    ),
    path(
        "form-files/<path:path>",
        views.field_file_download,
        name="field_file_download",
    ),
    path(
        "documents/<path:path>/download",
        views.ComplementaryDocumentDownloadView.as_view(),
        name="complementary_documents_download",
    ),
    path(
        "documents/<int:pk>/delete",
        views.submission_complementary_document_delete,
        name="complementary_documents_delete",
    ),
    path("", views.SubmissionList.as_view(), name="submissions_list"),
    path("", include(submission_urlpatterns + anonymous_submission_urlpatterns)),
    path(
        "media/<int:property_value_id>/",
        views.submission_media_download,
        name="submission_media_download",
    ),
    path(
        "adminentitiesgeojson/<int:administrative_entity_id>/",
        views.administrative_entities_geojson,
        name="administrative_entities_geojson",
    ),
    path("search/", views.submissions_search, name="submissions_search"),
    path(
        "archives/",
        views.ArchivedSubmissionListView.as_view(),
        name="archived_submission_list",
    ),
    path(
        "archives/<int:pk>/delete",
        views.ArchivedSubmissionDeleteView.as_view(),
        name="archived_submission_delete",
    ),
    path(
        "archives/<int:pk>/download",
        views.ArchivedSubmissionDownloadView.as_view(),
        name="archived_submission_download",
    ),
    path(
        "archives/bulk-download",
        views.ArchivedSubmissionBulkDownloadView.as_view(),
        name="archived_submission_bulk_download",
    ),
    path(
        "transactions/<str:merchant_reference>/change-status",
        views.ChangeTransactionStatus.as_view(),
        name="change_transaction_status",
    ),
    path(
        "transactions/confirm/<int:pk>",
        views.ConfirmTransactionCallback.as_view(),
        name="confirm_transaction",
    ),
    path(
        "transactions/fail/<int:pk>",
        views.FailTransactionCallback.as_view(),
        name="fail_transaction",
    ),
    path(
        "payment/<int:pk>",
        views.SubmissionPaymentRedirect.as_view(),
        name="submission_payment_redirect",
    ),
]

geocity/urls.py
import logging

from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

import geocity.apps.api.urls
from geocity.apps.accounts.dootix.provider import DootixProvider
from geocity.apps.accounts.geomapfish.provider import GeomapfishProvider
from geocity.apps.django_wfs3.urls import wfs3_router
from geocity.apps.submissions import views as submissions_views

from .views import legacy_urls_redirect

logger = logging.getLogger(__name__)

# See TWO_FACTOR_PATCH_ADMIN
if settings.ENABLE_2FA:
    from .admin_site_2fa import AdminSiteOTPRequiredMixinRedirSetup

    admin.site = AdminSiteOTPRequiredMixinRedirSetup()


# Django-configuration
urlpatterns = (
    [
        path("", submissions_views.submission_select_administrative_entity),
        path("submissions/", include("geocity.apps.submissions.urls")),
        path("reports/", include("geocity.apps.reports.urls")),
        # Backward compatibility for Geocity < 2.1, will be deprecated in 3.0
        re_path(r"permit-requests/.*", legacy_urls_redirect),
    ]
    + default_urlpatterns(GeomapfishProvider)
    + default_urlpatterns(DootixProvider)
)


urlpatterns += [
    path("", include("geocity.apps.accounts.urls")),
    path("rest/", include(geocity.apps.api.urls)),  # Django-rest urls
    path("wfs3/", include(wfs3_router.urls)),  # Django-rest urls
    path("captcha/", include("captcha.urls")),
    path("api-tokens/", include("knox.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("admin/", admin.site.urls),
    path("accounts/social/", include("allauth.socialaccount.urls")),
]

if settings.ENABLE_2FA:
    from two_factor.urls import urlpatterns as tf_urls

    urlpatterns += [
        path("", include(tf_urls)),
    ]

if settings.PREFIX_URL:
    urlpatterns = [path(settings.PREFIX_URL, include(urlpatterns))]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geocity/apps/submissions/models.py
import enum
import logging
import os
import tempfile
import urllib.parse
import zipfile
from datetime import date, datetime, timedelta

import PIL
import requests
from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.gis.db import models as geomodels
from django.contrib.gis.geos import GeometryCollection, MultiPoint, Point
from django.core.exceptions import SuspiciousOperation
from django.core.files import File
from django.core.validators import FileExtensionValidator
from django.db import models, transaction
from django.db.models import Count, F, JSONField, Max, Min, ProtectedError, Q, Value
from django.db.models.functions import Concat
from django.urls import reverse
from django.utils import timezone
from django.utils.dateparse import parse_date
from django.utils.functional import cached_property
from django.utils.html import escape, format_html
from django.utils.translation import gettext_lazy as _
from django_tables2.export import TableExport
from pdf2image import convert_from_path
from PIL import Image
from simple_history.models import HistoricalRecords

from geocity.apps.accounts.models import AdministrativeEntity, PermitDepartment, User
from geocity.apps.accounts.validators import validate_email
from geocity.apps.forms.models import Field, Form, FormCategory

from . import fields
from .contact_type_choices import *
from .payments.models import SubmissionPrice

# Actions
ACTION_AMEND = "amend"
ACTION_REQUEST_VALIDATION = "request_validation"
ACTION_VALIDATE = "validate"
ACTION_POKE = "poke"
ACTION_PROLONG = "prolong"
ACTION_COMPLEMENTARY_DOCUMENTS = "complementary_documents"
ACTION_REQUEST_INQUIRY = "request_inquiry"
ACTION_TRANSACTION = "transactins"
# If you add an action here, make sure you also handle it in `views.get_form_for_action`,  `views.handle_form_submission`
# and services.get_actions_for_administrative_entity
ACTIONS = [
    ACTION_AMEND,
    ACTION_REQUEST_VALIDATION,
    ACTION_VALIDATE,
    ACTION_POKE,
    ACTION_PROLONG,
    ACTION_COMPLEMENTARY_DOCUMENTS,
    ACTION_REQUEST_INQUIRY,
]

logger = logging.getLogger(__name__)


def printed_submission_storage(instance, filename):
    return f"permit_requests_uploads/{instance.submission.pk}/{filename}"


class GeoTimeInfo(enum.Enum):
    DATE = enum.auto()
    GEOMETRY = enum.auto()
    # Geometry automatically genrerate from address field using geoadmin API
    GEOCODED_GEOMETRY = enum.auto()


class SubmissionQuerySet(models.QuerySet):
    def filter_for_user(self, user, form_filter=None, ignore_archived=True):
        """
        Return the list of submissions this user has access to.
        """
        annotate_with = dict(
            starts_at_min=Min("geo_time__starts_at"),
            ends_at_max=Max("geo_time__ends_at"),
            permit_duration_max=Max("forms__permit_duration"),
            remaining_validations=Count("validations")
            - Count(
                "validations",
                filter=~Q(
                    validations__validation_status=SubmissionValidation.STATUS_REQUESTED
                ),
            ),
            required_validations=Count("validations"),
            author_fullname=Concat(
                F("author__first_name"),
                Value(" "),
                F("author__last_name"),
            ),
            author_details=Concat(
                F("author__email"),
                Value(" / "),
                F("author__userprofile__phone_first"),
                output_field=models.CharField(),
            ),
        )

        if form_filter is not None:
            annotate_with.update({"form_filter": Value(form_filter)})

        qs = self.annotate(**annotate_with)

        if ignore_archived:
            qs = qs.filter(~Q(status=Submission.STATUS_ARCHIVED))

        if not user.is_authenticated:
            return qs.none()

        if not user.is_superuser:
            qs_filter = Q(author=user)

            if user.has_perm("submissions.amend_submission") or user.has_perm(
                "submissions.read_submission"
            ):
                qs_filter |= Q(
                    administrative_entity__in=AdministrativeEntity.objects.associated_to_user(
                        user
                    ),
                ) & ~Q(status=Submission.STATUS_DRAFT)

            if user.has_perm("submissions.validate_submission"):
                qs_filter |= Q(
                    validations__department__in=PermitDepartment.objects.filter(
                        group__in=user.groups.all()
                    )
                )
            return qs.filter(qs_filter)

        return qs


class Submission(models.Model):
    STATUS_DRAFT = 0
    STATUS_SUBMITTED_FOR_VALIDATION = 1
    STATUS_APPROVED = 2
    STATUS_PROCESSING = 3
    STATUS_AWAITING_SUPPLEMENT = 4
    STATUS_AWAITING_VALIDATION = 5
    STATUS_REJECTED = 6
    STATUS_RECEIVED = 7
    STATUS_INQUIRY_IN_PROGRESS = 8
    STATUS_ARCHIVED = 9

    STATUS_CHOICES = (
        (STATUS_DRAFT, _("Brouillon")),
        (STATUS_SUBMITTED_FOR_VALIDATION, _("Envoyée, en attente de traitement")),
        (STATUS_AWAITING_SUPPLEMENT, _("Demande de compléments")),
        (STATUS_PROCESSING, _("En traitement")),
        (STATUS_AWAITING_VALIDATION, _("En validation")),
        (STATUS_APPROVED, _("Approuvée")),
        (STATUS_REJECTED, _("Refusée")),
        (STATUS_RECEIVED, _("Réceptionnée")),
        (STATUS_INQUIRY_IN_PROGRESS, _("Consultation publique en cours")),
        (STATUS_ARCHIVED, _("Archivée")),
    )
    AMENDABLE_STATUSES = {
        STATUS_SUBMITTED_FOR_VALIDATION,
        STATUS_PROCESSING,
        STATUS_AWAITING_SUPPLEMENT,
        STATUS_RECEIVED,
    }

    # Statuses that can be edited by pilot service if granted permission "edit_submission"
    EDITABLE_STATUSES = {
        STATUS_DRAFT,
        STATUS_AWAITING_SUPPLEMENT,
        STATUS_SUBMITTED_FOR_VALIDATION,
        STATUS_PROCESSING,
        STATUS_RECEIVED,
    }

    PROLONGABLE_STATUSES = {
        STATUS_APPROVED,
        STATUS_PROCESSING,
        STATUS_AWAITING_SUPPLEMENT,
    }

    # Statuses of submission visible in calendar (api => submissions_details)
    VISIBLE_IN_CALENDAR_STATUSES = {
        STATUS_APPROVED,
        STATUS_INQUIRY_IN_PROGRESS,
    }

    PROLONGATION_STATUS_PENDING = 0
    PROLONGATION_STATUS_APPROVED = 1
    PROLONGATION_STATUS_REJECTED = 2
    PROLONGATION_STATUS_CHOICES = (
        (PROLONGATION_STATUS_PENDING, _("En attente")),
        (PROLONGATION_STATUS_APPROVED, _("Approuvée")),
        (PROLONGATION_STATUS_REJECTED, _("Refusée")),
    )

    status = models.PositiveSmallIntegerField(
        _("état"), choices=STATUS_CHOICES, default=STATUS_DRAFT
    )
    shortname = models.CharField(
        _("nom court"),
        max_length=32,
        help_text=_(
            "Sera affiché dans le calendrier si la demande est rendue tout publique, ex: Brandons (max. 32 caractères)"
        ),
        blank=True,
    )
    created_at = models.DateTimeField(_("date de création"), default=timezone.now)
    validated_at = models.DateTimeField(_("date de validation"), null=True)
    forms = models.ManyToManyField(
        Form,
        through="SelectedForm",
        related_name="submissions",
        verbose_name=_("Formulaires"),
    )
    administrative_entity = models.ForeignKey(
        AdministrativeEntity,
        on_delete=models.CASCADE,
        verbose_name=_("entité administrative"),
        related_name="submissions",
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("auteur"),
        related_name="submissions",
    )
    contacts = models.ManyToManyField(
        "Contact", related_name="+", through="SubmissionContact"
    )
    validation_pdf = fields.SubmissionFileField(
        _("pdf de validation"),
        validators=[FileExtensionValidator(allowed_extensions=["pdf"])],
        upload_to="validations",
    )
    creditor_type = models.PositiveSmallIntegerField(
        _("Destinataire de la facture"),
        choices=CONTACT_TYPE_CHOICES,
        null=True,
        blank=True,
    )
    is_public = models.BooleanField(_("Publication calendrier"), default=False)
    prolongation_date = models.DateTimeField(
        _("Nouvelle date de fin"), null=True, blank=True
    )
    prolongation_comment = models.TextField(_("Commentaire"), blank=True)
    prolongation_status = models.PositiveSmallIntegerField(
        _("Décision"),
        choices=PROLONGATION_STATUS_CHOICES,
        null=True,
        blank=True,
    )
    additional_decision_information = models.TextField(
        _("Information complémentaire"),
        max_length=2048,
        blank=True,
        help_text=_("Facultative, sera transmise au requérant"),
    )

    history = HistoricalRecords()

    objects = SubmissionQuerySet().as_manager()

    class Meta:
        verbose_name = _("2.2 Consultation de la demande")
        verbose_name_plural = _("2.2 Consultation des demandes")
        permissions = [
            ("read_submission", _("Consulter les demandes")),
            ("amend_submission", _("Traiter les demandes")),
            ("validate_submission", _("Valider les demandes")),
            ("classify_submission", _("Classer les demandes")),
            ("edit_submission", _("Éditer les demandes")),
            ("view_private_form", _("Voir les demandes restreintes")),
            ("can_refund_transactions", _("Rembourser une transaction")),
            ("can_revert_refund_transactions", _("Revenir sur un remboursement")),
        ]
        indexes = [models.Index(fields=["created_at"])]

    def __str__(self):
        return self.shortname

    def is_draft(self):
        return self.status == self.STATUS_DRAFT

    def can_be_submitted_by_author(self):
        return self.can_be_edited_by_author()

    def can_be_edited_by_author(self):

geocity/apps/submissions/payments/postfinance/models.py
from simple_history.models import HistoricalRecords

from geocity.apps.submissions.payments.models import Transaction


class PostFinanceTransaction(Transaction):
    CHECKOUT_PROCESSOR_ID = "PostFinance"
    history = HistoricalRecords()

geocity/apps/submissions/templates/tables/_archived_submission_actions.html
{% load i18n %}
{% load submissions_extras %}

<ul class="list-inline text-right">
  {% can_download_archive as can_download %}
  {% if can_download %}
    <li>
      <a title="{% trans "Télécharger la demande" %}" href="{% url 'submissions:archived_submission_download' record.pk %}">
        <i class="fa fa-download fa-lg"></i>
      </a>
    </li>
  {% endif %}
  {% if record.archivist == request.user or request.user.is_superuser %}
    <li>
      <a title="{% trans "Supprimer la demande" %}" href="{% url 'submissions:archived_submission_delete' record.pk %}">
        <i class="fa fa-trash fa-lg"></i>
      </a>
    </li>
  {% endif %}
</ul>

geocity/apps/submissions/templates/tables/_submission_actions.html
{% load i18n %}
{% load submissions_extras %}

<ul class="list-inline">
  {% if record.author == request.user and not record.can_be_edited_by_author or can_view %}
  <li>
    <a title="{% trans "Voir" %}" href="{% url 'submissions:submission_detail' record.id %}">
      <i class="fa fa-eye fa-lg"></i>
    </a>
  </li>
  {% endif %}

  {% can_always_be_updated as can_update %}
  {% if record.author == request.user and record.can_be_edited_by_author or request.user.is_superuser or perms.submissions.edit_submission and record.can_be_edited_by_pilot or can_update %}
    <li>
      <a title="{% trans "Modifier" %}" href="{% url 'submissions:submission_fields' record.id %}">
        <i class="fa fa-edit fa-lg"></i>
      </a>
    </li>
  {% endif %}

  {% if record.author == request.user or request.user.is_superuser %}
    {% if record.can_be_deleted_by_author %}
      <li>
        <a title="{% trans "Supprimer la demande" %}" href="{% url 'submissions:submission_delete' record.id %}">
          <i class="fa fa-trash fa-lg"></i>
        </a>
      </li>
    {% endif %}
  {% endif %}

  {% if record.author == request.user or request.user.is_superuser %}
    {% if record.can_be_submitted_by_author %}
      <li>
        <a title="{% trans "Envoyer" %}" href="{% url 'submissions:submission_submit' record.id %}">
          <i class="fa fa-envelope fa-lg"></i>
        </a>
      </li>
    {% endif %}
  {% endif %}
  {% if record.can_be_prolonged %}
    {% if record.can_prolongation_be_requested %}
      {% if record.author == request.user %}
        <li>
          <a title="{% trans 'Demander une prolongation' %}" href="{% url 'submissions:submission_prolongation' record.id %}">
            <i class="fa fa-clock-o fa-lg"></i>
          </a>
        </li>
      {% endif %}
    {% else %}
      {# This icons might as well be shown to other users #}
      {% if record.prolongation_status == record.PROLONGATION_STATUS_PENDING %}
        <li>
          <i class="fa fa-clock-o fa-lg status0" title="{% trans 'Prolongation en attente' %} ({{ record.prolongation_date }})"></i>
        </li>
      {% elif record.prolongation_status == record.PROLONGATION_STATUS_REJECTED %}
        <li>
          <i class="fa fa-clock-o fa-lg status6" title="{% trans 'Prolongation refusée' %}"></i>
        </li>
      {% endif %}
    {% endif %}
  {% endif %}

</ul>

geocity/apps/submissions/templates/tables/_submission_author_details.html
{% load i18n %}
{% load submissions_extras %}

{% if not record.author.userprofile.is_anonymous %}
  {{ record.author.email }} / {{ record.author.userprofile.phone_first }} / {{ record.author.userprofile.address }}, {{ record.author.userprofile.zipcode }} {{ record.author.userprofile.city }}
{% else %}
  —
{% endif %}

geocity/apps/submissions/templates/tables/_submission_author_fullname.html
{% load i18n %}
{% load submissions_extras %}

{% if not record.author.userprofile.is_anonymous %}
  {{ record.author.userprofile }}
{% else %}
  —
{% endif %}

geocity/apps/submissions/templates/tables/_submission_author_iban.html
{% load i18n %}
{% load submissions_extras %}

{% if not record.author.userprofile.is_anonymous and record.author.userprofile.iban %}
  {{ record.author.userprofile.iban }}
{% else %}
  —
{% endif %}

geocity/apps/submissions/templates/tables/_submission_ends_at.html
{% load i18n %}
{% load submissions_extras %}

{% is_expired %}
{% if record.prolongation_date and record.prolongation_status == record.PROLONGATION_STATUS_APPROVED %}
    {{ record.prolongation_date }}
{% else %}
  {% if record.ends_at_max %}
      {{ record.ends_at_max }}
  {% else %}
    —
  {% endif %}
{% endif %}

geocity/apps/submissions/templates/tables/_submission_forms.html
{% for item in record.forms.all %}
  {% if record.form_filter == item.id|stringformat:"i"  %}
  <strong>{% endif %}{{ item.name }}{% if record.form_filter == item.id|stringformat:"i" %}
  </strong>{% endif %} ({{ item.category.name }}) <br />
{% endfor %}

geocity/apps/submissions/templates/tables/_submission_status.html
{% load i18n %}
{% if record.required_validations > 0 %}
  {% if record.remaining_validations > 0 %}
    <i class="fa fa-clock-o text-danger"></i>
    {% blocktrans trimmed with nb_remaining_validations=record.remaining_validations count nb_validations=record.required_validations %}
      {{ nb_validations }} validation en attente
    {% plural %}
      {{ nb_remaining_validations }}/{{ nb_validations }} validations en attente
    {% endblocktrans %}
  {% else %}
    {% if record.status == 2 or record.status == 4 or record.status == 6 %}
      <i class="fa fa-circle status{{record.status}}"></i> {{ record.get_status_display }}
    {% else %}
      <i class="fa fa-circle status{{record.status}}"></i> {% trans "Validée par les services" %}
    {% endif %}
  {% endif %}
{% else %}
  <i class="fa fa-circle status{{record.status}}"></i> {{ record.get_status_display }}
{% endif %}

geocity/apps/submissions/templates/tables/_submission_transactions_table_actions.html
{% load i18n %}
{% load submissions_extras %}

{% can_revert_refund_transaction as can_revert_refund %}
{% can_refund_transaction as can_refund %}

{% if can_revert_refund or can_refund %}
  {% if record.status != 'failed' %}
      <ul class="list-inline text-left">
        <li>
          <div class="form-group">
            <select class="form-control transactionStatusChangeSelect" id="transactionStatusChangeSelect-{{ record.merchant_reference }}">
              <option value="">--------</option>
              {% if can_refund %}
                {% if record.status != 'to_refund' and record.status != 'refunded' and record.status != 'failed' %}
                  <option value="to_refund">{% trans "A rembourser" %}</option>
                {% endif %}
                {% if record.status != 'refunded' and record.status != 'failed' %}
                  <option value="refunded">{% trans "Remboursée" %}</option>
                {% endif %}
              {% endif %}
              {% if can_revert_refund and record.status != 'paid' and record.status != 'failed' %}
                <option value="paid">{% trans "Payée" %}</option>
              {% endif %}
            </select>
          </div>
        </li>
        <li>
            <button class="btn btn-primary transactionStatusChangeBtn" data-href="{% url 'submissions:change_transaction_status' record.merchant_reference %}" data-merchant-reference="{{ record.merchant_reference }}">
              <i class="fa fa-save" style="pointer-events: none"></i>
            </button>
        </li>
      </ul>
    {% endif %}
{% endif %}