geocity/apps/submissions/urls.py
from django.urls import include, path

from . import views

app_name = "submissions"

submission_urlpatterns = [
    path(
        "administrative-entity/",
        views.submission_select_administrative_entity,
        name="submission_select_administrative_entity",
    ),
]

anonymous_submission_urlpatterns = [
    path(
        "anonymous/",
        views.anonymous_submission,
        name="anonymous_submission",
    ),
    path(
        "anonymous/sent",
        views.anonymous_submission_sent,
        name="anonymous_submission_sent",
    ),
]

existing_submission_urlpatterns = [
    path("", views.SubmissionDetailView.as_view(), name="submission_detail"),
    path(
        "objects/",
        views.submission_select_forms,
        name="submission_select_forms",
    ),
    path("properties/", views.submission_fields, name="submission_fields"),
    path("appendices/", views.submission_appendices, name="submission_appendices"),
    path("actors/", views.submission_contacts, name="submission_contacts"),
    path("submit/", views.submission_submit, name="submission_submit"),
    path(
        "submitconfirmed/",
        views.submission_submit_confirmed,
        name="submission_submit_confirmed",
    ),
    path("geotime/", views.submission_geo_time, name="submission_geo_time"),
    path("delete/", views.submission_delete, name="submission_delete"),
    path("approve/", views.submission_approve, name="submission_approve"),
    path("reject/", views.submission_reject, name="submission_reject"),
    path(
        "prolongation/",
        views.submission_prolongation,
        name="submission_prolongation",
    ),
]

urlpatterns = [
    path(
        "<int:submission_id>/",
        include(submission_urlpatterns + existing_submission_urlpatterns),
    ),
    # TODO: adapt path name here and in front app
    path(
        "permits-files/<path:path>",
        views.submission_file_download,
        name="submission_file_download",
    ),
    path(
        "form-files/<path:path>",
        views.field_file_download,
        name="field_file_download",
    ),
    path(
        "documents/<path:path>/download",
        views.ComplementaryDocumentDownloadView.as_view(),
        name="complementary_documents_download",
    ),
    path(
        "documents/<int:pk>/delete",
        views.submission_complementary_document_delete,
        name="complementary_documents_delete",
    ),
    path("", views.SubmissionList.as_view(), name="submissions_list"),
    path("", include(submission_urlpatterns + anonymous_submission_urlpatterns)),
    path(
        "media/<int:property_value_id>/",
        views.submission_media_download,
        name="submission_media_download",
    ),
    path(
        "adminentitiesgeojson/<int:administrative_entity_id>/",
        views.administrative_entities_geojson,
        name="administrative_entities_geojson",
    ),
    path("search/", views.submissions_search, name="submissions_search"),
    path(
        "archives/",
        views.ArchivedSubmissionListView.as_view(),
        name="archived_submission_list",
    ),
    path(
        "archives/<int:pk>/delete",
        views.ArchivedSubmissionDeleteView.as_view(),
        name="archived_submission_delete",
    ),
    path(
        "archives/<int:pk>/download",
        views.ArchivedSubmissionDownloadView.as_view(),
        name="archived_submission_download",
    ),
    path(
        "archives/bulk-download",
        views.ArchivedSubmissionBulkDownloadView.as_view(),
        name="archived_submission_bulk_download",
    ),
    path(
        "transactions/<str:merchant_reference>/change-status",
        views.ChangeTransactionStatus.as_view(),
        name="change_transaction_status",
    ),
    path(
        "transactions/confirm/<int:pk>",
        views.ConfirmTransactionCallback.as_view(),
        name="confirm_transaction",
    ),
    path(
        "transactions/fail/<int:pk>",
        views.FailTransactionCallback.as_view(),
        name="fail_transaction",
    ),
    path(
        "payment/<int:pk>",
        views.SubmissionPaymentRedirect.as_view(),
        name="submission_payment_redirect",
    ),
]

geocity/urls.py
import logging

from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

import geocity.apps.api.urls
from geocity.apps.accounts.dootix.provider import DootixProvider
from geocity.apps.accounts.geomapfish.provider import GeomapfishProvider
from geocity.apps.django_wfs3.urls import wfs3_router
from geocity.apps.submissions import views as submissions_views

from .views import legacy_urls_redirect

logger = logging.getLogger(__name__)

# See TWO_FACTOR_PATCH_ADMIN
if settings.ENABLE_2FA:
    from .admin_site_2fa import AdminSiteOTPRequiredMixinRedirSetup

    admin.site = AdminSiteOTPRequiredMixinRedirSetup()


# Django-configuration
urlpatterns = (
    [
        path("", submissions_views.submission_select_administrative_entity),
        path("submissions/", include("geocity.apps.submissions.urls")),
        path("reports/", include("geocity.apps.reports.urls")),
        # Backward compatibility for Geocity < 2.1, will be deprecated in 3.0
        re_path(r"permit-requests/.*", legacy_urls_redirect),
    ]
    + default_urlpatterns(GeomapfishProvider)
    + default_urlpatterns(DootixProvider)
)


urlpatterns += [
    path("", include("geocity.apps.accounts.urls")),
    path("rest/", include(geocity.apps.api.urls)),  # Django-rest urls
    path("wfs3/", include(wfs3_router.urls)),  # Django-rest urls
    path("captcha/", include("captcha.urls")),
    path("api-tokens/", include("knox.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("admin/", admin.site.urls),
    path("accounts/social/", include("allauth.socialaccount.urls")),
]

if settings.ENABLE_2FA:
    from two_factor.urls import urlpatterns as tf_urls

    urlpatterns += [
        path("", include(tf_urls)),
    ]

if settings.PREFIX_URL:
    urlpatterns = [path(settings.PREFIX_URL, include(urlpatterns))]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geocity/apps/submissions/models.py
import enum
import logging
import os
import tempfile
import urllib.parse
import zipfile
from datetime import date, datetime, timedelta

import PIL
import requests
from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.gis.db import models as geomodels
from django.contrib.gis.geos import GeometryCollection, MultiPoint, Point
from django.core.exceptions import SuspiciousOperation
from django.core.files import File
from django.core.validators import FileExtensionValidator
from django.db import models, transaction
from django.db.models import Count, F, JSONField, Max, Min, ProtectedError, Q, Value
from django.db.models.functions import Concat
from django.urls import reverse
from django.utils import timezone
from django.utils.dateparse import parse_date
from django.utils.functional import cached_property
from django.utils.html import escape, format_html
from django.utils.translation import gettext_lazy as _
from django_tables2.export import TableExport
from pdf2image import convert_from_path
from PIL import Image
from simple_history.models import HistoricalRecords

from geocity.apps.accounts.models import AdministrativeEntity, PermitDepartment, User
from geocity.apps.accounts.validators import validate_email
from geocity.apps.forms.models import Field, Form, FormCategory

from . import fields
from .contact_type_choices import *
from .payments.models import SubmissionPrice

# Actions
ACTION_AMEND = "amend"
ACTION_REQUEST_VALIDATION = "request_validation"
ACTION_VALIDATE = "validate"
ACTION_POKE = "poke"
ACTION_PROLONG = "prolong"
ACTION_COMPLEMENTARY_DOCUMENTS = "complementary_documents"
ACTION_REQUEST_INQUIRY = "request_inquiry"
ACTION_TRANSACTION = "transactins"
# If you add an action here, make sure you also handle it in `views.get_form_for_action`,  `views.handle_form_submission`
# and services.get_actions_for_administrative_entity
ACTIONS = [
    ACTION_AMEND,
    ACTION_REQUEST_VALIDATION,
    ACTION_VALIDATE,
    ACTION_POKE,
    ACTION_PROLONG,
    ACTION_COMPLEMENTARY_DOCUMENTS,
    ACTION_REQUEST_INQUIRY,
]

logger = logging.getLogger(__name__)


def printed_submission_storage(instance, filename):
    return f"permit_requests_uploads/{instance.submission.pk}/{filename}"


class GeoTimeInfo(enum.Enum):
    DATE = enum.auto()
    GEOMETRY = enum.auto()
    # Geometry automatically genrerate from address field using geoadmin API
    GEOCODED_GEOMETRY = enum.auto()


class SubmissionQuerySet(models.QuerySet):
    def filter_for_user(self, user, form_filter=None, ignore_archived=True):
        """
        Return the list of submissions this user has access to.
        """
        annotate_with = dict(
            starts_at_min=Min("geo_time__starts_at"),
            ends_at_max=Max("geo_time__ends_at"),
            permit_duration_max=Max("forms__permit_duration"),
            remaining_validations=Count("validations")
            - Count(
                "validations",
                filter=~Q(
                    validations__validation_status=SubmissionValidation.STATUS_REQUESTED
                ),
            ),
            required_validations=Count("validations"),
            author_fullname=Concat(
                F("author__first_name"),
                Value(" "),
                F("author__last_name"),
            ),
            author_details=Concat(
                F("author__email"),
                Value(" / "),
                F("author__userprofile__phone_first"),
                output_field=models.CharField(),
            ),
        )

        if form_filter is not None:
            annotate_with.update({"form_filter": Value(form_filter)})

        qs = self.annotate(**annotate_with)

        if ignore_archived:
            qs = qs.filter(~Q(status=Submission.STATUS_ARCHIVED))

        if not user.is_authenticated:
            return qs.none()

        if not user.is_superuser:
            qs_filter = Q(author=user)

            if user.has_perm("submissions.amend_submission") or user.has_perm(
                "submissions.read_submission"
            ):
                qs_filter |= Q(
                    administrative_entity__in=AdministrativeEntity.objects.associated_to_user(
                        user
                    ),
                ) & ~Q(status=Submission.STATUS_DRAFT)

            if user.has_perm("submissions.validate_submission"):
                qs_filter |= Q(
                    validations__department__in=PermitDepartment.objects.filter(
                        group__in=user.groups.all()
                    )
                )
            return qs.filter(qs_filter)

        return qs


class Submission(models.Model):
    STATUS_DRAFT = 0
    STATUS_SUBMITTED_FOR_VALIDATION = 1
    STATUS_APPROVED = 2
    STATUS_PROCESSING = 3
    STATUS_AWAITING_SUPPLEMENT = 4
    STATUS_AWAITING_VALIDATION = 5
    STATUS_REJECTED = 6
    STATUS_RECEIVED = 7
    STATUS_INQUIRY_IN_PROGRESS = 8
    STATUS_ARCHIVED = 9

    STATUS_CHOICES = (
        (STATUS_DRAFT, _("Brouillon")),
        (STATUS_SUBMITTED_FOR_VALIDATION, _("Envoyée, en attente de traitement")),
        (STATUS_AWAITING_SUPPLEMENT, _("Demande de compléments")),
        (STATUS_PROCESSING, _("En traitement")),
        (STATUS_AWAITING_VALIDATION, _("En validation")),
        (STATUS_APPROVED, _("Approuvée")),
        (STATUS_REJECTED, _("Refusée")),
        (STATUS_RECEIVED, _("Réceptionnée")),
        (STATUS_INQUIRY_IN_PROGRESS, _("Consultation publique en cours")),
        (STATUS_ARCHIVED, _("Archivée")),
    )
    AMENDABLE_STATUSES = {
        STATUS_SUBMITTED_FOR_VALIDATION,
        STATUS_PROCESSING,
        STATUS_AWAITING_SUPPLEMENT,
        STATUS_RECEIVED,
    }

    # Statuses that can be edited by pilot service if granted permission "edit_submission"
    EDITABLE_STATUSES = {
        STATUS_DRAFT,
        STATUS_AWAITING_SUPPLEMENT,
        STATUS_SUBMITTED_FOR_VALIDATION,
        STATUS_PROCESSING,
        STATUS_RECEIVED,
    }

    PROLONGABLE_STATUSES = {
        STATUS_APPROVED,
        STATUS_PROCESSING,
        STATUS_AWAITING_SUPPLEMENT,
    }

    # Statuses of submission visible in calendar (api => submissions_details)
    VISIBLE_IN_CALENDAR_STATUSES = {
        STATUS_APPROVED,
        STATUS_INQUIRY_IN_PROGRESS,
    }

    PROLONGATION_STATUS_PENDING = 0
    PROLONGATION_STATUS_APPROVED = 1
    PROLONGATION_STATUS_REJECTED = 2
    PROLONGATION_STATUS_CHOICES = (
        (PROLONGATION_STATUS_PENDING, _("En attente")),
        (PROLONGATION_STATUS_APPROVED, _("Approuvée")),
        (PROLONGATION_STATUS_REJECTED, _("Refusée")),
    )

    status = models.PositiveSmallIntegerField(
        _("état"), choices=STATUS_CHOICES, default=STATUS_DRAFT
    )
    shortname = models.CharField(
        _("nom court"),
        max_length=32,
        help_text=_(
            "Sera affiché dans le calendrier si la demande est rendue tout publique, ex: Brandons (max. 32 caractères)"
        ),
        blank=True,
    )
    created_at = models.DateTimeField(_("date de création"), default=timezone.now)
    validated_at = models.DateTimeField(_("date de validation"), null=True)
    forms = models.ManyToManyField(
        Form,
        through="SelectedForm",
        related_name="submissions",
        verbose_name=_("Formulaires"),
    )
    administrative_entity = models.ForeignKey(
        AdministrativeEntity,
        on_delete=models.CASCADE,
        verbose_name=_("entité administrative"),
        related_name="submissions",
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("auteur"),
        related_name="submissions",
    )
    contacts = models.ManyToManyField(
        "Contact", related_name="+", through="SubmissionContact"
    )
    validation_pdf = fields.SubmissionFileField(
        _("pdf de validation"),
        validators=[FileExtensionValidator(allowed_extensions=["pdf"])],
        upload_to="validations",
    )
    creditor_type = models.PositiveSmallIntegerField(
        _("Destinataire de la facture"),
        choices=CONTACT_TYPE_CHOICES,
        null=True,
        blank=True,
    )
    is_public = models.BooleanField(_("Publication calendrier"), default=False)
    prolongation_date = models.DateTimeField(
        _("Nouvelle date de fin"), null=True, blank=True
    )
    prolongation_comment = models.TextField(_("Commentaire"), blank=True)
    prolongation_status = models.PositiveSmallIntegerField(
        _("Décision"),
        choices=PROLONGATION_STATUS_CHOICES,
        null=True,
        blank=True,
    )
    additional_decision_information = models.TextField(
        _("Information complémentaire"),
        max_length=2048,
        blank=True,
        help_text=_("Facultative, sera transmise au requérant"),
    )

    history = HistoricalRecords()

    objects = SubmissionQuerySet().as_manager()

    class Meta:
        verbose_name = _("2.2 Consultation de la demande")
        verbose_name_plural = _("2.2 Consultation des demandes")
        permissions = [
            ("read_submission", _("Consulter les demandes")),
            ("amend_submission", _("Traiter les demandes")),
            ("validate_submission", _("Valider les demandes")),
            ("classify_submission", _("Classer les demandes")),
            ("edit_submission", _("Éditer les demandes")),
            ("view_private_form", _("Voir les demandes restreintes")),
            ("can_refund_transactions", _("Rembourser une transaction")),
            ("can_revert_refund_transactions", _("Revenir sur un remboursement")),
        ]
        indexes = [models.Index(fields=["created_at"])]

    def __str__(self):
        return self.shortname

    def is_draft(self):
        return self.status == self.STATUS_DRAFT

    def can_be_submitted_by_author(self):
        return self.can_be_edited_by_author()

    def can_be_edited_by_author(self):

geocity/apps/submissions/payments/postfinance/models.py
from simple_history.models import HistoricalRecords

from geocity.apps.submissions.payments.models import Transaction


class PostFinanceTransaction(Transaction):
    CHECKOUT_PROCESSOR_ID = "PostFinance"
    history = HistoricalRecords()

geocity/apps/submissions/templates/submissions/_directives_and_legal.html
{% load i18n %}
{% load bootstrap4 %}

{% if directives %}
  <div id="legal-infos">
    <h5>{% trans "Informations importantes" %}</h5>
    {% for directive_file, directive_description, additional_information in directives %}
      <div{% if not forloop.last %} class="mb-3"{% endif %}>
        {% if directive_file and directive_description %}
          <span class="directive_description">{{ directive_description }}</span>:
          <i class="fa fa-download" aria-hidden="true"></i>
          <a class="directive_file" href="{{ directive_file.url }}" target="_blank"
            rel="noreferrer">{% trans "Télécharger la directive" %}</a>
          <br>
        {% endif %}
        {% if additional_information %}
          <span class="additional_information">{{ additional_information|safe }}</span>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endif %}

geocity/apps/submissions/templates/submissions/_directives_and_legal_cta.html
{% load i18n %}
{% load bootstrap4 %}

{% if directives %}
  <button class="btn btn-outline-primary mb-2" type="button" data-toggle="collapse" data-target="#directives-and-legal-card" aria-expanded="false" aria-controls="directives-and-legal-card">
    <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
    {% trans "Informations importantes" %}
  </button>
  <div class="collapse" id="directives-and-legal-card">
    {% include "submissions/_directives_and_legal.html" %}
  </div>
{% endif %}

geocity/apps/submissions/templates/submissions/_submission_prices.html
{% if submission.requires_online_payment and submission.get_form_for_payment.requires_online_payment %}
    <div class="card mb-3" style="border-radius:0">
      <div class="card-header">{{ submission.get_form_for_payment.payment_settings.prices_label }}</div>
      <div class="card-body">
        {{ prices_form.as_table }}
      </div>
    </div>
{% endif %}

geocity/apps/submissions/templates/submissions/_submission_progressbar.html
{% load static %}

{% if steps %}
  <ul class="progress-nav mb-4">
    {% for step_key, step in steps.items %}
      <li class="progress-nav-item
        {% if step_key == active_step %} progress-nav-item-active{% endif %}
        {% if step.enabled %}progress-nav-item-enabled{% endif %}
        {% if step.completed and step.enabled %}progress-nav-item-done{% endif %}
        {% if step.errors_count and step.enabled %}progress-nav-item-partial{% endif %}
        ">
        {% if step.url and step.enabled %}
          <a class="progress-nav-link" href="{{ step.url }}">
        {% endif %}

        <div class="circle">
          {% if step.errors_count and step.enabled %}<div class="pill">{{ step.errors_count }}</div>{% endif %}
          <div class="circle-inner">
            {{ forloop.counter }}
          </div>
        </div>
        <br>

        {# Wrap the step name so it’s easier to extract in the tests #}
        <span class="step-name">
          {{ step.name }}
        </span>

        {% if step.url and step.enabled %}
          </a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endif %}

geocity/apps/submissions/templates/submissions/_submission_summary.html
{% load i18n %}
{% load bootstrap4 %}
{% load submissions_extras %}

<div class="container">
  <div class="row">
    <div class="col">
      {% for form, fields, appendices, amend_custom_fields in forms_infos %}
        <h4 class="workObjectHeader"> {{ form }} </h4>
        <div class="container">
          <dl class="properties-list">
            {% for field in fields %}
              {% if field.label %}
                <dt> {{ field.label }} </dt>
                <dd> {{ field.value|human_field_value|linebreaksbr }} </dd>
              {% else %}
                <dt style="white-space: nowrap;">{{ field.repr|safe }}</dt>
                <dd></dd>
              {% endif %}
            {% endfor %}

            {% for field in appendices %}
              <dt>{{ field.label }}</dt>
              <dd>
                {% if not field.value %}
                  <em>{% trans "Information non fournie" %}</em>
                {% else %}
                  <i class="fa fa-download pt-1 mr-1" aria-hidden="true"></i>
                  <a href="{{ field.value.url }}" rel="noreferrer" target="_blank">{% trans "Télécharger le document" %}</a>
                {% endif %}
              </dd>
            {% endfor %}
          </dl>
        </div>

        {% if amend_custom_fields %}
          <div class="container">
            <h5>{% trans "Informations du service responsable" %}</h5>
            {% for field_value in amend_custom_fields %}
              {% if field_value.field.is_visible_by_author or field_value.field.is_visible_by_validators and is_validator %}
                <dl class="properties-list">
                  <dt class="amend-property">{{ field_value.field }}</dt>
                  <dd>{{ field_value.value|linebreaksbr }}</dd>
                </dl>
              {% endif %}
            {% endfor %}
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>


  {% if contacts %}

    <div class="row">
      <div class="col">
        <div class="container">
          <h4>{% trans "Contacts" %}</h4>
            <dl>
              {% if requires_payment %}
                <dt>Destinataire de la facture</dt>
                <dd> {{ creditor }} </dd>
              {% endif %}
            </dl>
        </div>

          {% for contact_type, contact_infos in contacts %}
          <h5>{{ contact_type }}</h5>
            <div class="row">
              <div class="col">
                <div class="grid-container">
                  {% for field_label, field_value in contact_infos %}
                    {% if field_value %}
                    <div class="grid-element">
                      <dl>
                         <dt> {{ field_label }} </dt>
                         <dd> {{ field_value }} </dd>
                      </dl>
                    </div>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endfor %}

      </div>
    </div>

  {% endif %}

  <div class="row">
    <div class="col">
      {% for geo_time_form in geo_time_formset %}
        {{ geo_time_form.media }}
        {% include "submissions/_geo_time_form.html" with form=geo_time_form form_id=forloop.counter0 form_number=forloop.counter open=True %}
      {% endfor %}
    </div>
  </div>

  {% if documents %}
    <div class="row">
      <div class="col">
        <h2>Documents</h2>

        {% for document in documents %}
          <dl class="mb-4">
            <dt>{% trans "Nom" %}</dt>
            <dd>
                <div class="pl-0 col-10">
                  {{ document.document }}
                  {% if document.is_public %}
                    <span class="badge badge-pill badge-pill-55 badge-success">{% trans "Publique" %}</span>
                  {% endif %}
                </div>
                <div class="col-2 text-right">
                  <a class="align-middle" href="{% url 'submissions:complementary_documents_download' document.name %}"><i class="fa fa-download" aria-hidden="true"></i></a>
                  {% if user == document.owner and user != author or user.is_superuser %}
                    <form class="d-inline-block" method="post" action="{% url 'submissions:complementary_documents_delete' pk=document.id %}">
                      {% csrf_token %}
                      <button class="btn btn-link text-danger p-0" type="submit">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                      </button>
                    </form>
                  {% endif %}
                </div>
            </dd>

            <dt>{% trans "Statut" %}</dt>
            <dd>{{ document.get_status_display }}</dd>

            <dt>{% trans "Description" %}</dt>
            <dd>{{ document.description }}</dd>

            <dt>{% trans "Type" %}</dt>
            <dd>{{ document.document_type }}</dd>
          </dl>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}

      </div>
    </div>
  {% endif %}
</div>

geocity/apps/submissions/templates/submissions/archived_submission_list.html
{% extends "base_generic.html" %}

{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block content-fluid %}
  <div class="d-flex flex-column flex-md-row center-table">
    <div id="list-info-title">
      {% trans "Vue d'ensemble des demandes archivées" %}
    </div>
  </div>

  {% include "submissions/archived_submission_toolbox_header.html" %}

  <div class="permits-list center-table">
    {% render_table table %}
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'js/archived_request_bulk_download.js' %}"></script>
{% endblock %}

geocity/apps/submissions/templates/submissions/archived_submission_toolbox_header.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

<div class="d-flex flex-row center-table">
  <div class="p-2 permits-action-btns">
      <form id="download-form" method="get" action="{% url "submissions:archived_submission_bulk_download" %}">
        {% csrf_token %}
        <button class="btn btn-outline-primary" type="submit">
          <i class="fa fa-download"></i>
          {% trans "Télécharger" %}
        </button>
      </form>
  </div>
</div>

geocity/apps/submissions/templates/submissions/submission_anonymous_sent.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% load i18n %}
{% load submissions_extras %}

{% block content %}
  <h3>{% trans "Formulaire" %}</h3>
  <hr>
  <div class="card mb-3">
    <div class="card-body">
      <h4 class="card-title">{{ config.ANONYMOUS_REQUEST_SENT_TITLE }}</h4>
      <p>
        {{ config.ANONYMOUS_REQUEST_SENT_BODY }}
      </p>
    </div>
  </div>
{% endblock %}

geocity/apps/submissions/templates/submissions/submission_delete.html
{% extends "base_generic.html" %}

{% load i18n %}
{% load bootstrap4 %}

{% block content %}
  <h3 class="mt-2">{% trans "Effacer la demande ?" %}</h3>
  <form method="post">{% csrf_token %}
    <p>{% trans "Êtes vous sûr de vouloir supprimer la demande n°" %}{{ submission.id }} ?</p>
    <h4>{% trans "Détails de la demande:" %} </h4>
    <ul>
      <li>{% trans "Requérant:"%} {{ submission.author.first_name }}, {{ submission.author.last_name}}
      </li>
      <li>{% trans "Demande du:"%} {{ submission.created_at }}</li>
    </ul>
    {% bootstrap_button "Confirmer" button_type="submit" button_class="btn-primary" value="Confirmer" %}
    <a class="ml-2" href="{% url 'submissions:submissions_list' %}">{% trans "Annuler" %}</a>
  </form>
{% endblock %}

geocity/apps/submissions/templates/submissions/submission_select_administrative_entity.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% load i18n %}
{% load submissions_extras %}
{% load static %}


{% block content %}
  {% if submission %}
    {% submission_progressbar steps StepType.ADMINISTRATIVE_ENTITY %}
  {% endif %}
  <h3>{{ config.LOCATION_STEP }}</h3>

  {% if entityfilter and not user.userprofile.is_temporary %}
    {% trans "La liste ci-dessous est filtrée," %} <a href="{% url 'submissions:submission_select_administrative_entity' %}"><b>{% trans "voir toutes les possibilités" %}</b></a>
  {% endif %}

  <hr>
  <form method="post">
    {% bootstrap_form_errors form %}
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_field form.administrative_entity show_label=False %}

    {% buttons %}
      <button class="btn btn-primary">{% trans "Continuer" %}</button>
    {% endbuttons %}
  </form>
{% endblock %}