geocity/apps/reports/urls.py
from django.urls import path

from . import views

app_name = "reports"

urlpatterns = [
    path(
        "report/<int:submission_id>/<int:form_id>/<int:report_id>.html",
        views.report_content,
        name="submission_report_content",
    ),
    path(
        "report/<int:submission_id>/<int:form_id>/<int:report_id>/<int:transaction_id>.html",
        views.report_content,
        name="submission_report_content",
    ),
    path(
        "report/<int:submission_id>/<int:form_id>/<int:report_id>.pdf",
        views.report_pdf,
        name="submission_report_pdf",
    ),
    path(
        "report/<int:submission_id>/<int:form_id>/<int:report_id>/<int:transaction_id>.pdf",
        views.report_pdf,
        name="submission_report_pdf",
    ),
    path(
        "report/<path:path>/download",
        views.background_download,
        name="background_download",
    ),
]

geocity/urls.py
import logging

from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

import geocity.apps.api.urls
from geocity.apps.accounts.dootix.provider import DootixProvider
from geocity.apps.accounts.geomapfish.provider import GeomapfishProvider
from geocity.apps.django_wfs3.urls import wfs3_router
from geocity.apps.submissions import views as submissions_views

from .views import legacy_urls_redirect

logger = logging.getLogger(__name__)

# See TWO_FACTOR_PATCH_ADMIN
if settings.ENABLE_2FA:
    from .admin_site_2fa import AdminSiteOTPRequiredMixinRedirSetup

    admin.site = AdminSiteOTPRequiredMixinRedirSetup()


# Django-configuration
urlpatterns = (
    [
        path("", submissions_views.submission_select_administrative_entity),
        path("submissions/", include("geocity.apps.submissions.urls")),
        path("reports/", include("geocity.apps.reports.urls")),
        # Backward compatibility for Geocity < 2.1, will be deprecated in 3.0
        re_path(r"permit-requests/.*", legacy_urls_redirect),
    ]
    + default_urlpatterns(GeomapfishProvider)
    + default_urlpatterns(DootixProvider)
)


urlpatterns += [
    path("", include("geocity.apps.accounts.urls")),
    path("rest/", include(geocity.apps.api.urls)),  # Django-rest urls
    path("wfs3/", include(wfs3_router.urls)),  # Django-rest urls
    path("captcha/", include("captcha.urls")),
    path("api-tokens/", include("knox.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("admin/", admin.site.urls),
    path("accounts/social/", include("allauth.socialaccount.urls")),
]

if settings.ENABLE_2FA:
    from two_factor.urls import urlpatterns as tf_urls

    urlpatterns += [
        path("", include(tf_urls)),
    ]

if settings.PREFIX_URL:
    urlpatterns = [path(settings.PREFIX_URL, include(urlpatterns))]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geocity/apps/submissions/models.py
import enum
import logging
import os
import tempfile
import urllib.parse
import zipfile
from datetime import date, datetime, timedelta

import PIL
import requests
from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.gis.db import models as geomodels
from django.contrib.gis.geos import GeometryCollection, MultiPoint, Point
from django.core.exceptions import SuspiciousOperation
from django.core.files import File
from django.core.validators import FileExtensionValidator
from django.db import models, transaction
from django.db.models import Count, F, JSONField, Max, Min, ProtectedError, Q, Value
from django.db.models.functions import Concat
from django.urls import reverse
from django.utils import timezone
from django.utils.dateparse import parse_date
from django.utils.functional import cached_property
from django.utils.html import escape, format_html
from django.utils.translation import gettext_lazy as _
from django_tables2.export import TableExport
from pdf2image import convert_from_path
from PIL import Image
from simple_history.models import HistoricalRecords

from geocity.apps.accounts.models import AdministrativeEntity, PermitDepartment, User
from geocity.apps.accounts.validators import validate_email
from geocity.apps.forms.models import Field, Form, FormCategory

from . import fields
from .contact_type_choices import *
from .payments.models import SubmissionPrice

# Actions
ACTION_AMEND = "amend"
ACTION_REQUEST_VALIDATION = "request_validation"
ACTION_VALIDATE = "validate"
ACTION_POKE = "poke"
ACTION_PROLONG = "prolong"
ACTION_COMPLEMENTARY_DOCUMENTS = "complementary_documents"
ACTION_REQUEST_INQUIRY = "request_inquiry"
ACTION_TRANSACTION = "transactins"
# If you add an action here, make sure you also handle it in `views.get_form_for_action`,  `views.handle_form_submission`
# and services.get_actions_for_administrative_entity
ACTIONS = [
    ACTION_AMEND,
    ACTION_REQUEST_VALIDATION,
    ACTION_VALIDATE,
    ACTION_POKE,
    ACTION_PROLONG,
    ACTION_COMPLEMENTARY_DOCUMENTS,
    ACTION_REQUEST_INQUIRY,
]

logger = logging.getLogger(__name__)


def printed_submission_storage(instance, filename):
    return f"permit_requests_uploads/{instance.submission.pk}/{filename}"


class GeoTimeInfo(enum.Enum):
    DATE = enum.auto()
    GEOMETRY = enum.auto()
    # Geometry automatically genrerate from address field using geoadmin API
    GEOCODED_GEOMETRY = enum.auto()


class SubmissionQuerySet(models.QuerySet):
    def filter_for_user(self, user, form_filter=None, ignore_archived=True):
        """
        Return the list of submissions this user has access to.
        """
        annotate_with = dict(
            starts_at_min=Min("geo_time__starts_at"),
            ends_at_max=Max("geo_time__ends_at"),
            permit_duration_max=Max("forms__permit_duration"),
            remaining_validations=Count("validations")
            - Count(
                "validations",
                filter=~Q(
                    validations__validation_status=SubmissionValidation.STATUS_REQUESTED
                ),
            ),
            required_validations=Count("validations"),
            author_fullname=Concat(
                F("author__first_name"),
                Value(" "),
                F("author__last_name"),
            ),
            author_details=Concat(
                F("author__email"),
                Value(" / "),
                F("author__userprofile__phone_first"),
                output_field=models.CharField(),
            ),
        )

        if form_filter is not None:
            annotate_with.update({"form_filter": Value(form_filter)})

        qs = self.annotate(**annotate_with)

        if ignore_archived:
            qs = qs.filter(~Q(status=Submission.STATUS_ARCHIVED))

        if not user.is_authenticated:
            return qs.none()

        if not user.is_superuser:
            qs_filter = Q(author=user)

            if user.has_perm("submissions.amend_submission") or user.has_perm(
                "submissions.read_submission"
            ):
                qs_filter |= Q(
                    administrative_entity__in=AdministrativeEntity.objects.associated_to_user(
                        user
                    ),
                ) & ~Q(status=Submission.STATUS_DRAFT)

            if user.has_perm("submissions.validate_submission"):
                qs_filter |= Q(
                    validations__department__in=PermitDepartment.objects.filter(
                        group__in=user.groups.all()
                    )
                )
            return qs.filter(qs_filter)

        return qs


class Submission(models.Model):
    STATUS_DRAFT = 0
    STATUS_SUBMITTED_FOR_VALIDATION = 1
    STATUS_APPROVED = 2
    STATUS_PROCESSING = 3
    STATUS_AWAITING_SUPPLEMENT = 4
    STATUS_AWAITING_VALIDATION = 5
    STATUS_REJECTED = 6
    STATUS_RECEIVED = 7
    STATUS_INQUIRY_IN_PROGRESS = 8
    STATUS_ARCHIVED = 9

    STATUS_CHOICES = (
        (STATUS_DRAFT, _("Brouillon")),
        (STATUS_SUBMITTED_FOR_VALIDATION, _("Envoyée, en attente de traitement")),
        (STATUS_AWAITING_SUPPLEMENT, _("Demande de compléments")),
        (STATUS_PROCESSING, _("En traitement")),
        (STATUS_AWAITING_VALIDATION, _("En validation")),
        (STATUS_APPROVED, _("Approuvée")),
        (STATUS_REJECTED, _("Refusée")),
        (STATUS_RECEIVED, _("Réceptionnée")),
        (STATUS_INQUIRY_IN_PROGRESS, _("Consultation publique en cours")),
        (STATUS_ARCHIVED, _("Archivée")),
    )
    AMENDABLE_STATUSES = {
        STATUS_SUBMITTED_FOR_VALIDATION,
        STATUS_PROCESSING,
        STATUS_AWAITING_SUPPLEMENT,
        STATUS_RECEIVED,
    }

    # Statuses that can be edited by pilot service if granted permission "edit_submission"
    EDITABLE_STATUSES = {
        STATUS_DRAFT,
        STATUS_AWAITING_SUPPLEMENT,
        STATUS_SUBMITTED_FOR_VALIDATION,
        STATUS_PROCESSING,
        STATUS_RECEIVED,
    }

    PROLONGABLE_STATUSES = {
        STATUS_APPROVED,
        STATUS_PROCESSING,
        STATUS_AWAITING_SUPPLEMENT,
    }

    # Statuses of submission visible in calendar (api => submissions_details)
    VISIBLE_IN_CALENDAR_STATUSES = {
        STATUS_APPROVED,
        STATUS_INQUIRY_IN_PROGRESS,
    }

    PROLONGATION_STATUS_PENDING = 0
    PROLONGATION_STATUS_APPROVED = 1
    PROLONGATION_STATUS_REJECTED = 2
    PROLONGATION_STATUS_CHOICES = (
        (PROLONGATION_STATUS_PENDING, _("En attente")),
        (PROLONGATION_STATUS_APPROVED, _("Approuvée")),
        (PROLONGATION_STATUS_REJECTED, _("Refusée")),
    )

    status = models.PositiveSmallIntegerField(
        _("état"), choices=STATUS_CHOICES, default=STATUS_DRAFT
    )
    shortname = models.CharField(
        _("nom court"),
        max_length=32,
        help_text=_(
            "Sera affiché dans le calendrier si la demande est rendue tout publique, ex: Brandons (max. 32 caractères)"
        ),
        blank=True,
    )
    created_at = models.DateTimeField(_("date de création"), default=timezone.now)
    validated_at = models.DateTimeField(_("date de validation"), null=True)
    forms = models.ManyToManyField(
        Form,
        through="SelectedForm",
        related_name="submissions",
        verbose_name=_("Formulaires"),
    )
    administrative_entity = models.ForeignKey(
        AdministrativeEntity,
        on_delete=models.CASCADE,
        verbose_name=_("entité administrative"),
        related_name="submissions",
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("auteur"),
        related_name="submissions",
    )
    contacts = models.ManyToManyField(
        "Contact", related_name="+", through="SubmissionContact"
    )
    validation_pdf = fields.SubmissionFileField(
        _("pdf de validation"),
        validators=[FileExtensionValidator(allowed_extensions=["pdf"])],
        upload_to="validations",
    )
    creditor_type = models.PositiveSmallIntegerField(
        _("Destinataire de la facture"),
        choices=CONTACT_TYPE_CHOICES,
        null=True,
        blank=True,
    )
    is_public = models.BooleanField(_("Publication calendrier"), default=False)
    prolongation_date = models.DateTimeField(
        _("Nouvelle date de fin"), null=True, blank=True
    )
    prolongation_comment = models.TextField(_("Commentaire"), blank=True)
    prolongation_status = models.PositiveSmallIntegerField(
        _("Décision"),
        choices=PROLONGATION_STATUS_CHOICES,
        null=True,
        blank=True,
    )
    additional_decision_information = models.TextField(
        _("Information complémentaire"),
        max_length=2048,
        blank=True,
        help_text=_("Facultative, sera transmise au requérant"),
    )

    history = HistoricalRecords()

    objects = SubmissionQuerySet().as_manager()

    class Meta:
        verbose_name = _("2.2 Consultation de la demande")
        verbose_name_plural = _("2.2 Consultation des demandes")
        permissions = [
            ("read_submission", _("Consulter les demandes")),
            ("amend_submission", _("Traiter les demandes")),
            ("validate_submission", _("Valider les demandes")),
            ("classify_submission", _("Classer les demandes")),
            ("edit_submission", _("Éditer les demandes")),
            ("view_private_form", _("Voir les demandes restreintes")),
            ("can_refund_transactions", _("Rembourser une transaction")),
            ("can_revert_refund_transactions", _("Revenir sur un remboursement")),
        ]
        indexes = [models.Index(fields=["created_at"])]

    def __str__(self):
        return self.shortname

    def is_draft(self):
        return self.status == self.STATUS_DRAFT

    def can_be_submitted_by_author(self):
        return self.can_be_edited_by_author()

    def can_be_edited_by_author(self):

geocity/apps/reports/templates/reports/sections/_section.html
{% if section.is_new_page %}
  <div class="pagebreak"> </div>
{% endif %}
<div class="section {{section.css_class}}" style="padding-top: {{section.padding_top}}px;">
  {% if section.title %}
    <div class="title {{section.title_size}}">{% block title %}{% endblock title %}</div>
  {% endif %}
  {% block content %}
  {% endblock content %}
</div>

geocity/apps/reports/templates/reports/sections/sectionamendproperty.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if request_data.properties.amend_fields %}
        <div class="flex_container">
            <div class="flex_item-100">
                {% for form, commentaires in request_data.properties.amend_fields.items %}
                    <h3>{{form}}</h3>
                    {% for key, commentaire in commentaires.items %}
                        <span class="bold">{{key}} : </span>{{commentaire}}<br>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>Aucun contact pour cette demande</p>
    {% endif %}
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionauthor.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if submission.author %}
        <div class="flex_container">
            <div class="flex_item-100">
                <span class="bold">Prénom : </span>{{submission.author.first_name}}<br>
                <span class="bold">Nom : </span>{{submission.author.last_name}}<br>
                <span class="bold">Adresse : </span>{{submission.author.userprofile.address}}<br>
                <span class="bold">NPA : </span>{{submission.author.userprofile.zipcode}}<br>
                <span class="bold">Localité : </span>{{submission.author.userprofile.city}}<br>
                <span class="bold">Raison sociale : </span>{{submission.author.userprofile.company_name}}<br>
                <span class="bold">Numéro TVA : </span>{{submission.author.userprofile.vat_number}}<br>
                <span class="bold">Téléphone : </span>{{submission.author.userprofile.phone_first}}<br>
                <span class="bold">Téléphone : </span>{{submission.author.userprofile.phone_second}}<br>
                <span class="bold">E-mail : </span>{{submission.author.email}}<br>
                {% if settings.AUTHOR_IBAN_VISIBLE %}
                    <span class="bold">IBAN : </span>{{submission.author.userprofile.iban}}<br>
                {% endif %}
            </div>
        </div>
    {% else %}
        <p>Information non fournie</p>
    {% endif %}
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectioncontact.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if request_data.properties.contacts %}
        <div class="flex_container">
            {% for type, contact in request_data.properties.contacts.items %}
                <div class="flex_item-50">
                    <span class="bold">Type : </span>{{contact.contact_type_display}}<br>
                    <span class="bold">Prénom : </span>{{contact.first_name}}<br>
                    <span class="bold">Nom : </span>{{contact.last_name}}<br>
                    <span class="bold">Adresse : </span>{{contact.address}}<br>
                    <span class="bold">NPA : </span>{{contact.zipcode}}<br>
                    <span class="bold">Localité : </span>{{contact.city}}<br>
                    <span class="bold">Raison sociale : </span>{{contact.company_name}}<br>
                    <span class="bold">Numéro TVA : </span>{{contact.vat_number}}<br>
                    <span class="bold">Téléphone : </span>{{contact.phone}}<br>
                    <span class="bold">E-mail : </span>{{contact.email}}<br>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Aucun contact pour cette demande</p>
    {% endif %}
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectioncreditor.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if submission.get_creditor_type_display %}
        <div class="flex_container">
            <div class="flex_item-100">
                <p>{{submission.get_creditor_type_display}}</p>
            </div>
        </div>
    {% else %}
        <p>Auteur de la demande</p>
    {% endif %}
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectiondetail.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if request_data.properties.submission_fields %}
        <div class="flex_container">
            <div class="flex_item-100">
                {% if section.style == 0 %}
                    {% for form, fields in request_data.properties.submission_fields.items %}
                        {% if section.show_form_name %}
                            <h3>{{form}}</h3>
                        {% endif %}
                        {% for key, field in fields.items %}
                            {% if not key in section.undesired_properties %}
                                <div style="padding-top:{{section.line_height}}px;"><span class="bold">{{key}} : </span>{{field}}<br></div>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
            </div>
                {% elif  section.style == 1 %}
            </div>
                    {% for form, fields in request_data.properties.submission_fields.items %}
                        {% if section.show_form_name %}
                            <h3>{{form}}</h3>
                        {% endif %}
                        {% for key, field in fields.items %}
                            {% if not key in section.undesired_properties %}
                                <div class="flex_item-40"><span class="bold">{{key}}</span></div>
                                <div class="flex_item-60">{{field}}</div>
                                <div style="padding-top:{{section.line_height}}px;"></div>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                {% endif %}
        </div>
    {% else %}
        <p>Aucune propriété pour cette demande</p>
    {% endif %}
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionhorizontalrule.html
{% extends "reports/sections/_section.html" %}

{% block content %}
    <hr>
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionmap.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    <img src="{{map_data_url}}" />
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionparagraph.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}


{% block content %}
    <div class="flex_container">
        {% if section.location == "content" %}
            <div class="flex_item-100" style="text-align:{{section.text_align}}; text-justify: inter-character;">
                {{rendered_content}}
            </div>
        {% endif %}

        {% if section.location == "left" %}
            <div class="flex_item-50" style="text-align:{{section.text_align}}; text-justify: inter-character;">
                {{rendered_content}}
            </div>
            <div class="flex_item-50">
            </div>
        {% endif %}

        {% if section.location == "right" %}
            <div class="flex_item-50">
            </div>
            <div class="flex_item-50" style="text-align:{{section.text_align}}; text-justify: inter-character;">
                {{rendered_content}}
            </div>
        {% endif %}

    </div>
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionplanning.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if request_data.properties.geotime_aggregated %}
        <div class="flex_container">
            <div class="flex_item-100">
                <span class="bold">Date de début : </span>{{request_data.properties.geotime_aggregated.start_date}}<br>
                <span class="bold">Date de fin : </span>{{request_data.properties.geotime_aggregated.end_date}}<br>
                {% if request_data.properties.geotime_aggregated.comments %}
                    <span class="bold">Commentaire·s : </span><ul>
                        {% for comment in request_data.properties.geotime_aggregated.comments %}
                            <li>{{comment}}</li>
                        {% endfor %}
                    </ul><br>
                {% endif %}
                {% if request_data.properties.geotime_aggregated.external_links %}
                    <span span class="bold">Lien·s externe·s : </span><ul>
                        {% for link in request_data.properties.geotime_aggregated.external_links %}
                            <li><a href="{{link}}">{{link}}</a></li>
                        {% endfor %}
                    </ul><br>
                {% endif %}
            </div>
        </div>
    {% else %}
        <p>Aucun planning pour cette demande</p>
    {% endif %}
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionrecipient.html
{% extends "reports/sections/_section.html" %}

{% block content %}
    <div class="flex_container" style="padding-top: {{section.padding_top_recipient}}px;">
        <div class="flex_item-60">
        </div>
        {% if section.uses_dynamic_recipient %}
            {% comment %} {{dynamic_recipient}} {% endcomment %}
            <div class="flex_item-40" style="text-align: left;">
                {% if section.is_recommended %}
                    <span class="bold">RECOMMANDEE</span><br>
                {% endif %}
                {% if dynamic_recipient.company_name %}
                    {{dynamic_recipient.company_name}}<br>
                {% endif %}
                {{dynamic_recipient.last_name}} {{dynamic_recipient.first_name}}<br>
                {{dynamic_recipient.address}}<br>
                {{dynamic_recipient.zipcode}} {{dynamic_recipient.city}}
            </div>
        {% else %}
            <div class="flex_item-40" style="text-align: left;">
                {% if section.is_recommended %}
                    <span class="bold">RECOMMANDEE</span><br>
                {% endif %}
                {% if submission.author.userprofile.company_name %}
                    {{submission.author.userprofile.company_name}}<br>
                {% endif %}
                {{submission.author.last_name}} {{submission.author.first_name}}<br>
                {{submission.author.userprofile.address}}<br>
                {{submission.author.userprofile.zipcode}} {{submission.author.userprofile.city}}
            </div>
        {% endif %}
    </div>
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionstatus.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    <div class="flex_container">
        <div class="flex_item-100">
            <span class="bold">Statut : {{request_data.properties.status_display}}</span>
        </div>
    </div>
{% endblock %}

geocity/apps/reports/templates/reports/sections/sectionvalidation.html
{% extends "reports/sections/_section.html" %}

{% block title %}
    {{section.title}}
{% endblock %}

{% block content %}
    {% if request_data.properties.validations %}
        <div class="flex_container">
            <div class="flex_item-100">
                {% for service, validation in request_data.properties.validations.items %}
                <h3>Validation: {{service}}</h3>
                <span class="bold">Statut : </span>{{validation.validation_status}}<br>
                <span class="bold">Commentaire (avant) : </span>{{validation.comment_before}}<br>
                <span class="bold">Commentaire (pendant) : </span>{{validation.comment_during}}<br>
                <span class="bold">Commentaire (après) : </span>{{validation.comment_after}}<br>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>Aucune propriété pour cette demande</p>
    {% endif %}
{% endblock %}